version: '2'
services:
  database:
    container_name: maestro_database
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    env_file: "./docker/config/.env"
  nginx:
    container_name: maestro_server
    image: nginx:1
    ports:
      - "8010:80"
    volumes:
      - "./:/var/www"
      - "./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
  php:
    container_name: maestro_php
    build: ./docker/config/php
    image: container/php:v1
    depends_on:
      - database
    volumes:
      - "./:/var/www"
      - "./docker/config/php/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
#   tunnel for remote ssh
    ports:
      - "2225:22"
  phpmyadmin:
    container_name: maestro_pma
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    env_file: "./docker/config/.env"
    ports:
      - "8011:80"
